### PR TITLE
Voxel means

### PR DESCRIPTION
**Pull request by ChristosT**
Brings in the work of the `voxel-means` branch and adds a barplot of the data:

Screenshot from 2024-09-19 15-58-22

### CODE REVIEW

**Comment by ChristosT** [comment]
cc: @psavery

**Comment by psavery** [comment]
Hey Christos! This is looking great! Thanks for this effort. Just a few things:

1. Can you make the plotly plot shorter (smaller height)? I think it can be a relatively short plot. Right now, it extends below my window and adds a scroll bar:

image

2. Can you verify that the value being computed is a percent, and add a `%` sign? For this example we are using, the values in each voxel do indeed all sum up to 1. But can you make sure that these are percentages even when the voxels do not sum up to 1? You might have to modify the math a little bit.

**Comment by ChristosT** [comment]
@psavery these changes should do it. Let me know if something looks wrong

**Comment by psavery** [comment]
I still think it could be a little smaller in height, but we can worry about that later.

Can you resolve the merge conflict? And then it will be ready!

**Comment by ChristosT** [comment]
I have reduced the height and the conflict is resolved.

**Review by psavery — APPROVED** [review]

**Pull request merged**
